### PR TITLE
new feature: feature-pipeline::0.0.10

### PR DESCRIPTION
**Pull request by grupo1-devops-assistant**

### CODE REVIEW

**Review by fernandogutierrez27 — APPROVED** [review]

**Review by carlostognarell — APPROVED** [review]
machin de machin

**Review by anguitait — APPROVED** [review]

**Review by jesusdonoso — APPROVED** [review]
JD

**Review by MFrizR — APPROVED** [review]
ok

**Review by MrOscarDanilo — APPROVED** [review]
ok.

**Pull request merged**
