### PR TITLE
new feature: feature-pipeline

### PR DESCRIPTION
**Pull request by grupo1-devops-assistant**

### CODE REVIEW

**Review by fernandogutierrez27 — APPROVED** [review]
👍🏽

**Review by anguitait — COMMENTED** [review]
100

**Review by jesusdonoso — APPROVED** [review]

**Review by MFrizR — APPROVED** [review]
ok

**Review by MFrizR — APPROVED** [review]
ok

**Review by fernandogutierrez27 — APPROVED** [review]

**Review by anguitait — APPROVED** [review]
Check

**Review by jesusdonoso — APPROVED** [review]

**Review by carlostognarell — APPROVED** [review]
OK

**Review by MrOscarDanilo — APPROVED** [review]
ok.

**Pull request merged**
